<?php

if (function_exists('acf_add_local_field_group')) {
	
	// personas
	acf_add_local_field_group(array(
		'key' => 'group_610b595988896',
		'title' => 'Personas',
		'fields' => array(
			array(
				'key' => 'field_610b5a715baa0',
				'label' => 'Personas',
				'name' => 'personas',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 1,
				'max' => 0,
				'layout' => 'block',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_610b596b00856',
						'label' => 'Photo',
						'name' => 'photo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => 'editor-pic',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => 600,
						'min_height' => '',
						'min_size' => '',
						'max_width' => 1200,
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_611348e09e454',
						'label' => 'Information',
						'name' => 'lines',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_610b5ab75baa1',
								'label' => 'Line 1',
								'name' => 'line1',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'line1',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'Example: Ale José Yunuen',
								'prepend' => '',
								'append' => '',
								'maxlength' => 140,
							),
							array(
								'key' => 'field_610b5f9bc7ebf',
								'label' => 'Line 2',
								'name' => 'line2',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_610b5ab75baa1',
											'operator' => '!=empty',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'Example: Collection Development Librarian',
								'prepend' => '',
								'append' => '',
								'maxlength' => 140,
							),
							array(
								'key' => 'field_61109bbe789ff',
								'label' => 'Line 3',
								'name' => 'line3',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_610b5f9bc7ebf',
											'operator' => '!=empty',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'Example: United Kingdom',
								'prepend' => '',
								'append' => '',
								'maxlength' => 140,
							),
						),
					),
					array(
						'key' => 'field_61109c5ce400f',
						'label' => 'Link',
						'name' => 'profile_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/oeg-people-grid',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	// Testimonials
	acf_add_local_field_group(array(
		'key' => 'group_619fbba12e6c1',
		'title' => 'Testimonial Slider',
		'fields' => array(
			array(
				'key' => 'field_619fbbb9cdba2',
				'label' => 'Testimonio',
				'name' => 'testimonial',
				'type' => 'repeater',
				'instructions' => 'Agregue testimonios aquí...',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 1,
				'max' => 10,
				'layout' => 'row',
				'button_label' => 'Agregar testimonio',
				'sub_fields' => array(
					array(
						'key' => 'field_619fbc05cdba3',
						'label' => 'Cita',
						'name' => 'quote',
						'type' => 'textarea',
						'instructions' => 'Escriba o pegue el texto aquí...',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'La educación es lo que queda después de que uno haya olvidado lo que ha aprendido en la escuela.',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 5,
						'new_lines' => 'wpautop',
					),
					array(
						'key' => 'field_619fbc6fcdba4',
						'label' => 'Nombre',
						'name' => 'name',
						'type' => 'text',
						'instructions' => 'Escriba o pegue aquí el autor de la cita...',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Albert Einstein',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => 80,
					),
					array(
						'key' => 'field_619fbc9ecdba5',
						'label' => 'Autor',
						'name' => 'info',
						'type' => 'textarea',
						'instructions' => 'Escriba o pegue aquí la ocupación o ubicación de la persona...',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Escuela Politécnica Federal de Zúrich (diploma federal de enseñanza, 1900). Universidad de Zúrich (doctorado, 1905)',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
					),
					array(
						'key' => 'field_619fbcf2cdba6',
						'label' => 'Foto',
						'name' => 'photo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => 'ts-thumb',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => 200,
						'min_height' => '',
						'min_size' => '',
						'max_width' => 1500,
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_619fc2659c742',
						'label' => 'citar',
						'name' => 'cite',
						'type' => 'url',
						'instructions' => 'Pegue aquí el enlace a la referencia...',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_619feb64585f3',
				'label' => 'Color de fondo',
				'name' => 'bg_color',
				'type' => 'color_picker',
				'instructions' => 'Seleccione el color de fondo del bloque de testimonios',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_61a65b4874600',
				'label' => 'Color de texto',
				'name' => 'text_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#333333',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/oeg-testimonial-slider',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
}
